baseURL = "http://vivendo.tech/"
languageCode = "pt-br"
title = "Vivendo tech"
defaultContentLanguage = "pt-BR"

pygmentsCodeFences = true   # Enable triple backtick 'code fence' markdown
pygmentsUseClasses = false  # Add inline styles, no need to compile extra CSS

pygmentsStyle = "dracula"
googleAnalytics = "UA-90999033-3"
copyright = "Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    tabWidth = 2

[[menu.main]]
    name = "Dados"
    identifier = "dados"
    url = "/dados/"

[[menu.main]]
    name = "Linguagens"
    identifier = "linguagens"
    url = "/linguagens/"

[[menu.main]]
    name = "Software"
    identifier = "software"
    url = "/software/"

[[menu.main]]
    name = "Web"
    identifier = "web"
    url = "/web/"    

[author]
    name = "João Antônio Marcolan"

paginate = 12 

